# Generated by Django 5.1.2 on 2024-11-02 12:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageBoard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscribers', models.ManyToManyField(blank=True, related_name='messageboard', to=settings.AUTH_USER_MODEL, verbose_name='Subscriptores')),
            ],
            options={
                'verbose_name': 'Subscriptor',
                'verbose_name_plural': 'Subscriptores',
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('body', models.CharField(max_length=2000, verbose_name='Cuerpo')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creado')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to=settings.AUTH_USER_MODEL, verbose_name='Autor')),
                ('messageboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='a_messageboard.messageboard', verbose_name='Dashboard de mensajes')),
            ],
            options={
                'verbose_name': 'Mensaje',
                'verbose_name_plural': 'Mensajes',
                'ordering': ['-created'],
            },
        ),
    ]
